/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class RpcClient extends UnbufferedContactable {
  private long swigCPtr;

  protected RpcClient(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.RpcClient_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RpcClient obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_RpcClient(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RpcClient() {
    this(yarpJNI.new_RpcClient(), true);
  }

  public boolean addOutput(String name) {
    return yarpJNI.RpcClient_addOutput__SWIG_0(swigCPtr, this, name);
  }

  public boolean addOutput(String name, String carrier) {
    return yarpJNI.RpcClient_addOutput__SWIG_1(swigCPtr, this, name, carrier);
  }

  public boolean addOutput(Contact contact) {
    return yarpJNI.RpcClient_addOutput__SWIG_2(swigCPtr, this, Contact.getCPtr(contact), contact);
  }

  public void close() {
    yarpJNI.RpcClient_close(swigCPtr, this);
  }

  public void interrupt() {
    yarpJNI.RpcClient_interrupt(swigCPtr, this);
  }

  public void resume() {
    yarpJNI.RpcClient_resume(swigCPtr, this);
  }

  public Contact where() {
    return new Contact(yarpJNI.RpcClient_where(swigCPtr, this), true);
  }

  public String getName() {
    return yarpJNI.RpcClient_getName(swigCPtr, this);
  }

  public boolean write(PortWriter writer, PortWriter callback) {
    return yarpJNI.RpcClient_write__SWIG_0(swigCPtr, this, PortWriter.getCPtr(writer), writer, PortWriter.getCPtr(callback), callback);
  }

  public boolean write(PortWriter writer) {
    return yarpJNI.RpcClient_write__SWIG_1(swigCPtr, this, PortWriter.getCPtr(writer), writer);
  }

  public boolean write(PortWriter writer, PortReader reader, PortWriter callback) {
    return yarpJNI.RpcClient_write__SWIG_2(swigCPtr, this, PortWriter.getCPtr(writer), writer, PortReader.getCPtr(reader), reader, PortWriter.getCPtr(callback), callback);
  }

  public boolean write(PortWriter writer, PortReader reader) {
    return yarpJNI.RpcClient_write__SWIG_3(swigCPtr, this, PortWriter.getCPtr(writer), writer, PortReader.getCPtr(reader), reader);
  }

  public boolean read(PortReader reader, boolean willReply) {
    return yarpJNI.RpcClient_read__SWIG_0(swigCPtr, this, PortReader.getCPtr(reader), reader, willReply);
  }

  public boolean read(PortReader reader) {
    return yarpJNI.RpcClient_read__SWIG_1(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public boolean reply(PortWriter writer) {
    return yarpJNI.RpcClient_reply(swigCPtr, this, PortWriter.getCPtr(writer), writer);
  }

  public boolean replyAndDrop(PortWriter writer) {
    return yarpJNI.RpcClient_replyAndDrop(swigCPtr, this, PortWriter.getCPtr(writer), writer);
  }

  public boolean setEnvelope(PortWriter envelope) {
    return yarpJNI.RpcClient_setEnvelope(swigCPtr, this, PortWriter.getCPtr(envelope), envelope);
  }

  public boolean getEnvelope(PortReader envelope) {
    return yarpJNI.RpcClient_getEnvelope(swigCPtr, this, PortReader.getCPtr(envelope), envelope);
  }

  public int getInputCount() {
    return yarpJNI.RpcClient_getInputCount(swigCPtr, this);
  }

  public int getOutputCount() {
    return yarpJNI.RpcClient_getOutputCount(swigCPtr, this);
  }

  public void getReport(PortReport reporter) {
    yarpJNI.RpcClient_getReport(swigCPtr, this, PortReport.getCPtr(reporter), reporter);
  }

  public void setReporter(PortReport reporter) {
    yarpJNI.RpcClient_setReporter(swigCPtr, this, PortReport.getCPtr(reporter), reporter);
  }

  public boolean isWriting() {
    return yarpJNI.RpcClient_isWriting(swigCPtr, this);
  }

  public void setReader(PortReader reader) {
    yarpJNI.RpcClient_setReader(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public SWIGTYPE_p_Type getType() {
    return new SWIGTYPE_p_Type(yarpJNI.RpcClient_getType(swigCPtr, this), true);
  }

  public void promiseType(SWIGTYPE_p_Type typ) {
    yarpJNI.RpcClient_promiseType(swigCPtr, this, SWIGTYPE_p_Type.getCPtr(typ));
  }

  public Property acquireProperties(boolean readOnly) {
    long cPtr = yarpJNI.RpcClient_acquireProperties(swigCPtr, this, readOnly);
    return (cPtr == 0) ? null : new Property(cPtr, false);
  }

  public void releaseProperties(Property prop) {
    yarpJNI.RpcClient_releaseProperties(swigCPtr, this, Property.getCPtr(prop), prop);
  }

  public void setInputMode(boolean expectInput) {
    yarpJNI.RpcClient_setInputMode(swigCPtr, this, expectInput);
  }

  public void setOutputMode(boolean expectOutput) {
    yarpJNI.RpcClient_setOutputMode(swigCPtr, this, expectOutput);
  }

  public void setRpcMode(boolean expectRpc) {
    yarpJNI.RpcClient_setRpcMode(swigCPtr, this, expectRpc);
  }

  public boolean write(Bottle data1, Bottle data2) {
    return yarpJNI.RpcClient_write__SWIG_4(swigCPtr, this, Bottle.getCPtr(data1), data1, Bottle.getCPtr(data2), data2);
  }

}
